[workspace]
resolver = "2"
members = ["crates/main"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
authors = ["ARGVUS"]
repository = "https://github.com/argvus/argvus-removable-devices"
homepage = "https://github.com/argvus/argvus-removable-devices"
description = "Removable storage module for Waybar using UDisks2"

[profile.release]
lto = true
strip = true
